import os


global_vars = {'conceallevel': 2,
               'autowriteall': 1,
               'table_reduce_last_col': 0,
               'rxWord': '[^[:blank:]!"$%&''()*+,:;<=>?\[\]\\^`{}]*[^[:blank:]!"$%&''()*+.,:;<=>?\[\]\\^`{}]',
               'use_mouse': 0,
               'rxWikiInclSuffix': '}}',
               'html_header_numbering_sym': '',
               'hl_cb_checked': 0,
               'rxWikiInclUrl': '[^\\\}]\{-}',
               'ext2syntax': {'.markdown': 'markdown',
                              '.md': 'markdown',
                              '.mw': 'media',
                              '.mdwn': 'markdown',
                              '.mkdn': 'markdown',
                              '.mdown': 'markdown'},
               'auto_header': 0,
               'schemes_local': 'wiki\d\+\|diary\|local',
               'rxWikiLinkUrl': '[^\\\]]\{-}',
               'diary_months': {'11': 'November',
                                '1': 'January',
                                '2': 'February',
                                '3': 'March',
                                '4': 'April',
                                '5': 'May',
                                '6': 'June',
                                '7': 'July',
                                '8': 'August',
                                '9': 'September',
                                '12': 'December',
                                '10': 'October'},
               'rxWikiInclSeparator': '|',
               'rxWikiInclArg': '[^\\\}]\{-}',
               'hcolor_ctermfg_light': ['DarkRed',
                                        'DarkGreen',
                                        'DarkBlue',
                                        'Black',
                                        'Black',
                                        'Black'],
               'rx_wikilink_prefix1': '\[\[[^\\\]]\{-}|',
               'global_ext': 1,
               'WikiLinkTemplate1': '[[__LinkUrl__]]',
               'WikiLinkTemplate2': '[[__LinkUrl__|__LinkDescription__]]',
               'tags_header': 'GeneratedTags',
               'rx_wikilink_suffix1': '\]\]',
               'hcolor_ctermfg_dark': ['Red',
                                       'Green',
                                       'Blue',
                                       'White',
                                       'White',
                                       'White'],
               'rxWikiInclSuffix1': '\%(|[^\\\}]\{-}\)\{-}}}',
               'w32_dir_enc': '',
               'schemes_web': 'http\|https\|file\|ftp\|gopher\|telnet\|nntp\|ldap\|rsync\|imap\|pop\|irc\|ircs\|cvs\|svn\|svn+ssh\|git\|ssh\|fish\|sftp\|thunderlink\|message',
               'WikiInclTemplate1': '{{__LinkUrl__}}',
               'auto_chdir': 0,
               'html_header_numbering': 0,
               'filetypes': [],
               'rxWikiInclPrefix': '{{',
               'tags_header_level': 1,
               'rxWikiIncl': '{{[^\\\}]\{-}\%(|[^\\\}]\{-}\)\{-}}}',
               'table_auto_fmt': 1,
               'schemes_any': 'mailto\|matrix\|news\|xmpp\|sip\|sips\|doi\|urn\|tel\|data',
               'create_link': 1,
               'rx_wikilink_suffix': '\]\]',
               'listsyms': ' .oOX',
               'rxWeblinkUrl': '\%(\%(\%(http\|https\|file\|ftp\|gopher\|telnet\|nntp\|ldap\|rsync\|imap\|pop\|irc\|ircs\|cvs\|svn\|svn+ssh\|git\|ssh\|fish\|sftp\|thunderlink\|message\):\%(//\)\)\|\%(mailto\|matrix\|news\|xmpp\|sip\|sips\|doi\|urn\|tel\|data\):\)\S\{-1,}\%(([^ \t()]*)\)\=',
               'table_mappings': 1,
               'rx_wikilink_separator': '|',
               'CJK_length': 0,
               'key_mappings': {'headers': 1,
                                'table_format': 1,
                                'lists': 1,
                                'global': 1,
                                'lists_return': 1,
                                'links': 1,
                                'all_maps': 1,
                                'text_objs': 1,
                                'mouse': 0,
                                'table_mappings': 1,
                                'html': 1},
               'WikiInclTemplate2': '{{__LinkUrl__|__LinkDescription__}}',
               'links_header': 'Generated Links',
               'hl_headers': 0,
               'valid_html_tags': 'b,i,s,u,sub,sup,kbd,br,hr,div,center,strong,em',
               'listsym_rejected': '-',
               'rxWikiInclMatchUrl': '{{\zs[^\\\}]\{-}\ze\%(|[^\\\}]\{-}\)\{-}}}',
               'markdown_header_style': 1,
               'rxSchemes': '\%(wiki\d\+\|diary\|local\|http\|https\|file\|ftp\|gopher\|telnet\|nntp\|ldap\|rsync\|imap\|pop\|irc\|ircs\|cvs\|svn\|svn+ssh\|git\|ssh\|fish\|sftp\|thunderlink\|message\|mailto\|matrix\|news\|xmpp\|sip\|sips\|doi\|urn\|tel\|data\)',
               'map_prefix': '<Leader>w',
               'hcolor_guifg_light': ['#aa5858',
                                      '#507030',
                                      '#1030a0',
                                      '#103040',
                                      '#505050',
                                      '#636363'],
               'emoji_enable': 3,
               'links_header_level': 1,
               'rxWikiInclArgs': '\%(|[^\\\}]\{-}\)\{-}',
               'use_calendar': 1,
               'user_htmls': '',
               'conceal_onechar_markers': 1,
               'listing_hl_command': 'pygmentize -f html',
               'dir_link': '',
               'listing_hl': 0,
               'menu': 'Vimwiki',
               'conceal_pre': 0,
               'rx_wikilink_prefix': '\[\[',
               'rxWikiInclPrefix1': '{{[^\\\}]\{-}|',
               'hcolor_guifg_dark': ['#e08090',
                                     '#80e090',
                                     '#6090e0',
                                     '#c0c0f0',
                                     '#e0e0f0',
                                     '#f0f0f0'],
               'url_maxsave': 15,
               'rxWikiLinkDescr': '[^\\\]]\{-}',
               'folding': ''}

fg = 'color\s*:\s*__COLORFG__\s*;\s*'
bg = 'background\s*:\s*__COLORBG__\s*;\s*'
color_tag_rx = '<span \s*style\s*=\s*"\s*\(' + fg + bg + '\|' + fg + \
        '\|' + bg + '\)"\s*>__CONTENT__<\/span>'

local_vars = {'auto_diary_index': {'type': type(0),
                                   'default': 0,
                                   'min': 0,
                                   'max': 1},
                      'auto_export': {'type': type(0),
                                      'default': 0,
                                      'min': 0,
                                      'max': 1},
                      'auto_generate_links': {'type': type(0),
                                              'default': 0,
                                              'min': 0,
                                              'max': 1},
                      'auto_generate_tags': {'type': type(0),
                                             'default': 0,
                                             'min': 0,
                                             'max': 1},
                      'auto_tags': {'type': type(0),
                                    'default': 0,
                                    'min': 0,
                                    'max': 1},
                      'auto_toc': {'type': type(0),
                                   'default': 0,
                                   'min': 0,
                                   'max': 1},
                      'automatic_nested_syntaxes': {'type': type(0),
                                                    'default': 1,
                                                    'min': 0,
                                                    'max': 1},
                      'base_url': {'type': type(''),
                                   'default': '',
                                   'min_length': 1},
                      'bullet_types': {'type': type([]),
                                       'default': []},
                      'color_dic': {'type': type({}),
                                    'default': {'default': ['', '#d79921'],
                                                'red': ['#cc241d', ''],
                                                'bred': ['', '#cc241d'],
                                                'green': ['#98971a', ''],
                                                'bgreen': ['', '#98971a'],
                                                'yellow': ['#d79921', ''],
                                                'byellow': ['', '#d79921'],
                                                'blue': ['#458588', ''],
                                                'bblue': ['', '#458588'],
                                                'purple': ['#b16286', ''],
                                                'bpurple': ['', '#b16286'],
                                                'orange': ['#d65d0e', ''],
                                                'borange': ['', '#d65d0e'],
                                                'gray': ['#a89984', ''],
                                                'bgray': ['', '#a89984']}},
                      'color_tag_template': {'type': type({}),
                                             'default': color_tag_rx},
                      'commentstring': {'type': type(''),
                                        'default': '%%%s'},
                      'css_name': {'type': type(''),
                                   'default': 'style.css',
                                   'min_length': 1},
                      'custom_wiki2html': {'type': type(''), 'default': ''},
                      'custom_wiki2html_args': {'type': type(''),
                                                'default': ''},
                      'cycle_bullets': {'type': type(0), 'default': 0},
                      'diary_frequency': {'type': type(''),
                                          'default': 'daily',
                                          'possible_values': ['daily',
                                                              'weekly',
                                                              'monthly',
                                                              'yearly']},
                      'diary_start_week_day': {'type': type(''),
                                               'default': 'monday',
                                               'possible_values': ['monday',
                                                                   'tuesday',
                                                                   'wednesday',
                                                                   'thursday',
                                                                   'friday',
                                                                   'saturday',
                                                                   'sunday']},
                      'diary_header': {'type': type(''),
                                       'default': 'Diary',
                                       'min_length': 1},
                      'diary_index': {'type': type(''),
                                      'default': 'diary',
                                      'min_length': 1},
                      'diary_rel_path': {'type': type(''),
                                         'default': 'diary/',
                                         'min_length': 0},
                      'diary_caption_level': {'type': type(0),
                                              'default': 0,
                                              'min': -1,
                                              'max': 6},
                      'diary_sort': {'type': type(''),
                                     'default': 'desc',
                                     'possible_values': ['asc', 'desc']},
                      'exclude_files': {'type': type([]), 'default': []},
                      'ext': {'type': type(''),
                              'default': '.wiki',
                              'min_length': 1},
                      'html_filename_parameterization': {'type': type(0),
                                                         'default': 0,
                                                         'min': 0,
                                                         'max': 1},
                      'generated_links_caption': {'type': type(0),
                                                  'default': 0},
                      'index': {'type': type(''),
                                'default': 'index',
                                'min_length': 1},
                      'links_space_char': {'type': type(''),
                                           'default': ' ',
                                           'min_length': 1},
                      'list_ignore_newline': {'type': type(0),
                                              'default': 1,
                                              'min': 0,
                                              'max': 1},
                      'list_margin': {'type': type(0),
                                      'default': -1,
                                      'min': -1},
                      'listsym_rejected': {'type': type(''),
                                           'default': global_vars['listsym_rejected']},
                      'listsyms': {'type': type(''),
                                   'default': global_vars['listsyms']},
                      'listsyms_propagate': {'type': type(0), 'default': 1},
                      'markdown_link_ext': {'type': type(0),
                                            'default': 0,
                                            'min': 0,
                                            'max': 1},
                      'maxhi': {'type': type(0),
                                'default': 0,
                                'min': 0,
                                'max': 1},
                      'name': {'type': type(''), 'default': ''},
                      'nested_syntaxes': {'type': type({}), 'default': {}},
                      'path': {'type': type(''),
                               'default': os.path.expandvars('$HOME/vimwiki/'),
                               'min_length': 1},
                      'path_html': {'type': type(''), 'default': ''},
                      'rss_max_items': {'type': type(0),
                                        'default': 10,
                                        'min': 0},
                      'rss_name': {'type': type(''),
                                   'default': 'rss.xml',
                                   'min_length': 1},
                      'syntax': {'type': type(''),
                                 'default': 'default',
                                 'possible_values': ['default',
                                                     'markdown',
                                                     'media',
                                                     'mediawiki']},
                      'template_default': {'type': type(''),
                                           'default': 'default',
                                           'min_length': 1},
                      'template_ext': {'type': type(''), 'default': '.tpl'},
                      'template_path': {'type': type(''),
                                        'default': os.path.expandvars('$HOME/vimwiki/templates/')},
                      'template_date_format': {'type': type(''),
                                               'default': '%Y-%m-%d'},
                      'text_ignore_newline': {'type': type(0),
                                              'default': 1,
                                              'min': 0,
                                              'max': 1},
                      'tag_format': {'type': type({}),
                                     'default': {'pre': '^\|\s',
                                                 'pre_mark': ':',
                                                 'in': '[^:''[:space:]]\+',
                                                 'sep': ':',
                                                 'post_mark': ':',
                                                 'post': '\s\|$',
                                                 'conceal': 0,
                                                 'cchar': ''}},
                      'toc_header': {'type': type(''),
                                     'default': 'Contents',
                                     'min_length': 1},
                      'toc_header_level': {'type': type(0),
                                           'default': 1,
                                           'min': 1,
                                           'max': 6},
                      'toc_link_format': {'type': type(0),
                                          'default': 0,
                                          'min': 0,
                                          'max': 1},
                      'rx_todo': {'type': type(''),
                                  'default': '\C\<\%(TODO\|DONE\|STARTED\|FIXME\|FIXED\|XXX\)\>'}}
